_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: en
uuid: c684e80f-eb89-4372-bfae-9c729003f4cb
name: 'Innoraft Employee Management portal'
mail: swarnav.das@innoraft.com
slogan: ''
page:
  403: /node/2
  404: /node/1
  front: /node/3
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
